### ISSUE TITLE
No 5.2.7 build on launchpad for Xenial 16.04

### ISSUE THREAD

**Issue by lockie** [liballeg/allegro5#1276]
Hello! I'm using liballegro Xenial build from [the launchpad ppa](https://launchpad.net/~allegro) to make sure my game build runs on the widest range of old Linux distributions. Unfortunately, there is no newest 5.2.7 build for Xenial due to [some kind of liballegro_dialog related package bug](https://launchpad.net/~allegro/+archive/ubuntu/5.2/+build/21726297); the build log says
```
dh_install: liballegro-dialog5.2 missing files: usr/lib/*/liballegro_dialog.so.*
```
I suspect this is related to moving to GTK3 and this other line in the log:
```
- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
```
I have Xenial-based system handy, and it seems that it has the package called `libgtk-3-dev` which most probably will solve the issue.

**Comment by SiegeLord** [comment]
I tried that, but got an error:

```
../lib/liballegro_dialog.so.5.2.7: undefined reference to `gtk_menu_popup_at_widget'
```

Maybe the Xenial GTK3 is too old. Perhaps we could use a different function? Can you reproduce this error on your Xenial system?

**Comment by lockie** [comment]
Strangely enough, both on my Xenial-based Mint laptop and under `ubuntu:xenial` docker container, I was able to compile `liballegro_dialog` from 5.2.7.0 sources just fine, only having the warning about that function that reads
```
/tmp/allegro-5.2.7.0/addons/native_dialog/gtk_menu.c: In function 'do_show_popup_menu':
/tmp/allegro-5.2.7.0/addons/native_dialog/gtk_menu.c:390:7: warning: implicit declaration of function 'gtk_menu_popup_at_widget' [-Wimplicit-function-declaration]
       gtk_menu_popup_at_widget(args->menu->extra1, menu,  GDK_GRAVITY_SOUTH_WEST,
       ^
```
The `libgtk-3-dev` package version on both systems is `3.18.9-1ubuntu3.3`.
I wonder whether Launchpad build environment is somehow different from pristine Xenial install which exists in docker container.

**Comment by dos1** [comment]
If you got that warning, it means that build is likely broken anyway. Have you tried actually running anything that uses allegro-dialog on xenial?

**Comment by lockie** [comment]
@dos1 Oops, you're right: trying to compile ex_menu example from Allegro source tree, I'm getting
```
../lib/liballegro_dialog.so.5.2.7: undefined reference to `gtk_menu_popup_at_widget'
```
error from linker.

Indeed Gtk3 3.18 headers present in Xenial only define `gtk_menu_popup` (which was deprecated in later versions). I think I can provide a patch using `GTK_MINOR_VERSION` macro at compile time to decide the function to be called depending on GTK version, would that be appropriate?

**Comment by beoran** [comment]
It is probably better to use CMake to see if that function exists.

Op wo 18 aug. 2021 12:41 schreef Andrew Kravchuk ***@***.***>:

**Comment by lockie** [comment]
@beoran I beilive using preexisting tools will be simpler (like e.g. here https://github.com/csete/gpredict/commit/dea153c2245e395e13143263302a224eb81f17a0), since CMake will also add a macro for the function existence, and it will be the same approach, but with extra steps.

**Comment by SiegeLord** [comment]
I'd be fine with a patch like that. We can patch both Allegro source and the Ubuntu package.

**Comment by lockie** [comment]
The patch's ready and tested. I wasn't able to do the full Allegro build, having some errors from Physfs library (obviously being too old too), but I can see some `use-old-physfs.patch` in debian packaging process, so I believe this should not pose a problem.

**Comment by SiegeLord** [comment]
I updated the package and verified that it installs in a VM. Thanks for the bug report and patch!

**Comment by lockie** [comment]
Awesome, thank you @SiegeLord !
