### ISSUE TITLE
Build failure with OS X 10.11 SDK and earlier (error: use of undeclared identifier 'NSWindowStyleMaskTitled')

### ISSUE THREAD

**Issue by ryandesign** [liballeg/allegro5#1655]
allegro5 5.2.10.1 doesn't build when using the OS X (macOS) 10.11 SDK or earlier. The error is:

```
src/macosx/osxgl.m:673:52: error: use of undeclared identifier 'NSWindowStyleMaskTitled'
   [dpy->win setStyleMask: [dpy->win styleMask] & ~NSWindowStyleMaskTitled];
                                                   ^
```

This was reported to MacPorts here: https://trac.macports.org/ticket/72711

In the 10.11 SDK and earlier, these constants had different names. `NSWindowStyleMaskTitled` for example was called `NSTitledWindowMask`.

`NSTitledWindowMask` was changed to `NSWindowStyleMaskTitled` in f9f5a8ef01273aeba45175e6840c267bd959d135 thus introducing this bug.

It does build with the macOS 10.12 SDK and later however it is not always convenient for a user to use a newer SDK.

**Comment by SiegeLord** [comment]
Is that the only incompatibility? It's not a huge problem to change it. We in fact use NSTitledWindowMask elsewhere in the codebase, so a simple change of NSWindowStyleMaskTitled to NSTitledWindowMask would be a fine change.
